# -*- coding: utf-8 -*-
"""AI Lab-1 Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1He9fhs-nFRenJhd4sQa14q9v8ob1ZRLd
"""

import pandas as pd

df = pd.read_csv("/content/lab_label.txt")
df

df.head(5)

df.dtypes

df.describe()

df.isnull().sum()

df2 = pd.read_csv("/content/weather.numeric(1).csv")
df2

df2.isnull().sum()

df2["temperature"].fillna(1001, inplace = True)
df2

df2["windy"].value_counts()

df2["windy"].fillna("False", inplace = True)
df2

df2["humidity"].fillna(df2["humidity"].mean(), inplace = True)
df2

df2["play"].fillna("no", inplace = True)
df2

df2.isnull().sum()